### ISSUE TITLE
Troubles with Home Assistant Installation

### ISSUE THREAD

**Issue by dabbinavo** [Phunkafizer/RaspyRFM#11]
Hello @Phunkafizer,

I recently ordered your RFM69 ["Doppelmodul" from Seegel Systeme](https://www.seegel-systeme.de/2015/09/02/ein-funkmodul-fuer-den-raspberry-raspyrfm/) and am now trying to integrate it into my Home Assistant setup. My goal is to perform switch actions of my Intertechno IT-1500 plugs from the Home Assistant.

I want to extend my Raspberry Pi 3 that already runs Home Assistant:
- Installation was done using these instructions: [Install Home Assistant Operating System](https://www.home-assistant.io/installation/raspberrypi#install-home-assistant-operating-system)
- Host: `Home Assistant OS 7.6`
- Supervisor: `supervisor-2022.04.0`
- Core: `core-2022.4.5`

# 1st attempt: Home Assistant "raspyrfm" integration

My first attempt was to follow [these instructions](https://www.home-assistant.io/integrations/raspyrfm/) from the Home Assistant documentation.

I added the following to my `configuration.yaml`:
```yaml
switch:
  - platform: raspyrfm  # note: the online documentation has a missing dash here
    switches:
      - name: Intertechno Test
        controlunit_manufacturer: Intertechno
        controlunit_model: "IT-1500"
        channel_config:
          CODE: "01100010000110001101011110"  # note: quotes required here as otherwise the regex check from raspirfm-client fails cause leading numbers are removed by the yaml interpreter
          UNIT: 1
```

Unfortunately it simply does nothing. Also checked the SPI traces, but nothing happens.

Thought that maybe the SPI interface has to be enabled. So I inserted the RPI SD card into my computer and modified boot/config.txt (commented in `dtparam=spi=on`). -> still not working..

# 2nd attempt: Instructions from Seegel Systeme

Then I found the instructions ["Funksteckdosen, -sensoren und Fernbedienungen in Homeassistant integrieren"](https://www.seegel-systeme.de/2022/01/22/funksteckdosen-sensoren-und-fernbedienungen-in-homeassistant-integrieren/).

The page mentions, that it is possible to use the raspyrfm module on the same pi that runs the Home Assistant instance. Well, sounds good!

The page also says that the py must have the RaspyRFM python module installed. Unfortunately I am not able to perform the commands as [mentioned on the setup instructions](https://www.seegel-systeme.de/2015/09/02/ein-funkmodul-fuer-den-raspberry-raspyrfm/).

I am executing the commands in the integrated terminal of the [Studio Code Server Home Assistant AddOn](https://community.home-assistant.io/t/home-assistant-community-add-on-visual-studio-code/107863)

`sudo` commands do not work at all..:
```sh
sudo apt-get install git-core python3-dev python3-pip
```
-> `zsh: command not found: sudo`

```sh
apt-get install git-core python3-dev python3-pip
```
->
```Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'git' instead of 'git-core'
Package python3-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'python3-dev' has no installation candidate
E: Unable to locate package python3-pip```

```sh
git clone https://github.com/Phunkafizer/RaspyRFM.git
cd RaspyRFM
```
-> works

```sh
pip3 install -e .
```
->
```
Traceback (most recent call last):
  File "/usr/local/bin/pip3", line 5, in <module>
    from pip._internal.cli.main import main
  File "/usr/local/lib/python3.9/dist-packages/pip/_internal/cli/main.py", line 9, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/usr/local/lib/python3.9/dist-packages/pip/_internal/cli/autocompletion.py", line 10, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/usr/local/lib/python3.9/dist-packages/pip/_internal/cli/main_parser.py", line 8, in <module>
    from pip._internal.cli import cmdoptions
  File "/usr/local/lib/python3.9/dist-packages/pip/_internal/cli/cmdoptions.py", line 23, in <module>
    from pip._internal.cli.parser import ConfigOptionParser
  File "/usr/local/lib/python3.9/dist-packages/pip/_internal/cli/parser.py", line 12, in <module>
    from pip._internal.configuration import Configuration, ConfigurationError
  File "/usr/local/lib/python3.9/dist-packages/pip/_internal/configuration.py", line 26, in <module>
    from pip._internal.utils.logging import getLogger
  File "/usr/local/lib/python3.9/dist-packages/pip/_internal/utils/logging.py", line 27, in <module>
    from pip._internal.utils.misc import ensure_dir
  File "/usr/local/lib/python3.9/dist-packages/pip/_internal/utils/misc.py", line 39, in <module>
    from pip._internal.locations import get_major_minor_version
  File "/usr/local/lib/python3.9/dist-packages/pip/_internal/locations/__init__.py", line 14, in <module>
    from . import _distutils, _sysconfig
  File "/usr/local/lib/python3.9/dist-packages/pip/_internal/locations/_distutils.py", line 9, in <module>
    from distutils.cmd import Command as DistutilsCommand
ModuleNotFoundError: No module named 'distutils.cmd'
```

```sh
apps/rcpulsegw.py
```
->
```
Traceback (most recent call last):
  File "/config/custom_components/RaspyRFM/apps/rcpulsegw.py", line 4, in <module>
    from raspyrfm import *
ModuleNotFoundError: No module named 'raspyrfm'
```

# 3rd attempt: RaspyRFM on a cleanRaspberry Pi OS

Frustrated that nothing seems to work, I flashed a clean Raspberry Pi OS on another SD card and inserted it into the Raspberry Pi of the previous attempts that normally runs Home Assistant (with the RaspyRFM module still plugged in).

Cloned the RaspiRFM repo onto it, executed the setup instructions and after enabling SPI in Raspberry Pi config -> tada - it works. I ran the apps/rcpulse.py script with different parameters and was able to receive the RC pulses from the IT-1500 control and was able to switch the IT-1500 plugs from the PI. The RFM module seems to work perfectly. So, the hardware setup is fine. It has to do something with the software setup in combination with Home Assistant.

# My Question
So finally, my question is: How to make the system running? And why does nothing happen when setting the thing up like in the 1st attempt (not even receiving any signals on the SPI)? Who is the maintainer of this integration?

I would be so happy if you could help me @Phunkafizer! :)

**Comment by Phunkafizer** [comment]
Hi @dabbinavo & thanks for your report.

1. The "raspyrfm" integration was written by Markus Ressel: https://github.com/markusressel/raspyrfm-client
It is working in a very different way: It is generating UDP messages which are compatible to a connair or a itgw-433 controller which receive those UDP messages and generate radio telegrams from those. If you want to use this integration you have to run the "connair.py" script from my raspyrfm repository, which will emulate a connair controller. Markus' integration does not access the raspyrfm-hardware directly.

2. For my setup I use a default Raspberry Pi OS running homeassistant as a dockercontainer, in this case it is working without any problems. I will update the documentation that the HA raspberry image may not work, apperently some software parts are missing which are required.

3. If you just add a docker instance with home assistant it should be complete.

If you want to use the "MQTT-way" just run rcspulsegw.py and generate the MQTT messages via homeassistant. Of course you have to install a mqtt broker (possibly on the same raspberry).

Kind regards
Stefan
